sudo: false
language: node_js
node_js:
  - "6"

env:
  - secure: "KqfycFMq7Qm49Kv69pz6Ur7kCffvncQ/Y/yjwqh/HPMWs8OUmRlajhpRz3AM0+Y9b9GuxfMtWUrzZQ4JEd9QFZfcN6DCNAYRSms4wJm5El+P99R21GWQU33bS3V9RGtVeJdUxsjtlI9Spo6/0mac9MRURZbVUbhAgN3EPDliWCepXR61nl1re4ybSWh8mF7+eSpvPvfbwxl6nqtx+LlD5Nus55vk9AL2M3EALZma+QqlL4ulgvfs48fHfio9UazOjhjUJu4SbkCaSLNQohXZx6w/E1eVhOsqIaCUgcfg4H+C8DQ5wEH2FdMduS/HbcWe8vjKCehVepryzZ1m7+0pA5UFJgqnTPpbrw1kee9Ghn0BCnGRm08s7POYanrlbwn0o3ADCbbtwnD3H2EXxESVQ95DwV/7eeDF0iUQupqhJTpCqzjGNJq1Tgwf4PcVmcXF3mrysozh0Ba2REfm7zVIYHsQBEn5+LEfoColUXLthSGW3zMPY3bdlvCbChI8qE6Ztu58ulu4J5rnUtLZRyXYBVP7iMdecDhvOhgVqXu9PlfL02WD8kxnZLGUYWwgPB1XWwT6vsy9UpBGxqTKPoGHHm0l2JvUFkBWI9bNnRVGvqYot6tWGzeWQZ28YaKaMIMaTBFvdCM8wtkcizhc5GUeIzHt0CKw/X98x6dhk39tWao="

after_success:
  - |
      FLYNN_APP=""
      if [ "$TRAVIS_BRANCH" = "master" ]; then FLYNN_APP="www"; fi

      if [ "$FLYNN_APP" = "" ]; then echo "skipping branch $TRAVIS_BRANCH" && exit 0; fi

      git pull
      git remote add flynn https://user:$FLYNN_KEY@git.messagebot.io/$FLYNN_APP.git
      git push flynn master

script: npm run test
